language: node_js
os:
- osx
- linux
node_js: 14.0.0
before_install: if [[ `npm -v` != 6* ]]; then npm i -g npm@6; fi
install:
- |
  if [ $TRAVIS_OS_NAME == "linux" ]; then
    export DISPLAY=':99.0'
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  fi
script:
- |
  echo ">>> Installing Dependencies"
  npm install
  echo ">>> Compile create-compoenent   >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
  npm run compile
  echo ">>> Compiled create-component  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
after_script:
- |
  echo ">>> Publishing on marketplace"
  npm run deploy
stages:
- name: after_script
  if: env(TRAVIS_TAG) =~ ^v
cache: npm
env:
  global:
    secure: TVzdl/qo3GDOqGbKztXvwIXTFIyEHIIsYb3kN3TS2A/z4qWklqt85CihWCbNuIVgPbGzyTWGkrGbGskXYZES0mWUgqjr0AKKyljwfPXuAbmRDME53BsRgDUX3+ItEtTaN1Ps79gvAgEZQCpBrfnBLSC5M4ykpAbTRKzlh70iqVGThQ0OcPDfRGSEp98FNgrJBSOga/TbG0+TjfuMkovG/pvuueqldSUZJMs4M3JqSTkOt1iqB+jmK/ZVEGL19FFIJYBk8BY2H8j+wjpuHIzS+uEFats/qzJ/6QPJ/0FsgFMCAfLGA0JZnsXSxXw289/4XUF57gsLR/x4NOh65N8npInYvJB0jMCOWzJIy7SF8JK0BA0+7YuJle6+Ot46O0dJkU2If+HGfozKvTZuKcH71mq0cde6zOxym/B9HLQz1qJZb6lie8Y5QqE+Fb5NGdbLlot80u8wUyTZAvPAwR24zLP6m+9nF+3iwoesjtiX85vUrNauxx1FdDjbmIAXJvQS84BkYC8K8zEM47U8/HmAbdN+yPi+bJq4M7+zFqC9s3gwCiLlKSWv0WMltjImZ1d73JuX1D4aP6rhvH5Q4kQKHxPK2SGy5jrE9Z8O6iXgG68A2IZYuu2UTZq/stP/f9AENMUiTnvMHLTFuouHzihFDdtBDug76lnv98/o4zsBKyo=
