language: node_js
os:
- osx
- linux
node_js: 14.0.0
before_install: if [[ `npm -v` != 6* ]]; then npm i -g npm@6; fi
install:
- |
  if [ $TRAVIS_OS_NAME == "linux" ]; then
    export DISPLAY=':99.0'
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  fi
script:
- |
  echo ">>> Installing Dependencies"
  npm install
  echo ">>> Compile create-compoenent   >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
  npm run compile
  echo ">>> Compiled create-component  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
after_script:
- |
  echo ">>> Publishing on marketplace"
  npm run deploy
stages:
- name: after_script
  if: env(TRAVIS_TAG) =~ ^v
cache: npm
env:
  global:
    secure: L0Vbn1EjbNeoynCJZbT3gps0EtGJ6D0jwQ3Zf0a/r/rjeD0Z8Cb4rjYJavkOf4wLYgWw8KK3XK2tTI6ra/dxuwFaRKKb0MKY4/ak75XNKfunyTynvv91SHWyXuVzo7HWkj87Pbovy39rfvU8KvFWAyeFyb4/Su9dNPY5zQUHbZdXAZndcymjfhriqBFyTizwRGR7qwPmZadfUSH77QO4DdOUsuXbF8nHWOJFa/oW6vVdCdToE7rx0Ai2q/x6VuYzeQsJvZaIxfR47Az11jME7CU9ZT67V2QeVIm8/rd0B4zWaon055rmwa4AUnRekFaue1yB9E1AJWIVw/MwKapUmGYzqAzooIJTH/S7aaSjxx0HXb44DAe8O1/B3ZQHb62dInzavFk/NEzpPzS2aWuMnWBBuP4EiBfhfrk2SIbYa7jI2WZw9T1pNO67VzVY+rDwWMtSAD7lUgId+CaLT6aG74PSvGJIrNrPeQm5IsJ9lTBT7+fvjdrz1XaS7WDyIRjJ+/dqg84eBhGbSklS/9yM50sue0BDmFdZGGwhHG3XfS+ShdO/aotc8Kki/IuEbSBGxULTv5iB0qoiiucTBd93hte66oUfTiTWu0pdGwMw9E2JaNhtprjpP5/5EplJ409nNpaV783Y+pUq2ONXKvgJdFy7ceGMDXfEROi6iBplJo4=
